name: "release-build"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Release Build"
    runs-on: "macos-latest"

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          version: 16
      - name: "Build"
        run: |
          npm i
          GH_TOKEN=${{ secrets.GH_TOKEN }} npm run build

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          automatic_release_tag: "release"
          title: "Development Build"
          files: |
            LICENSE.txt
            dist/*.dmg
            dist/*.AppImage
            dist/*.exe
